BASE_COPY = "BASE_COPY"
DENSE_DELTA = "DENSE_DELTA"
QUANTIZED_DELTA = "QUANTIZED_DELTA"
LOW_RANK = "LOW_RANK"
SPARSE_PATCH = "SPARSE_PATCH"
LOW_RANK_PATCH = "LOW_RANK_PATCH"
COPY_FROM_TIED = "COPY_FROM_TIED"
NEURAL_BLOCK_FIELD = "NEURAL_BLOCK_FIELD"

SUPPORTED_OPCODES = {
    BASE_COPY,
    DENSE_DELTA,
    QUANTIZED_DELTA,
    LOW_RANK,
    SPARSE_PATCH,
    LOW_RANK_PATCH,
    COPY_FROM_TIED,
    NEURAL_BLOCK_FIELD,
}
